### ISSUE TITLE
How to use dates in axis labels?

### ISSUE THREAD

**Issue by koheiw** [xuan-liang/ggmatplot#17]
Thank you for developing the extremely useful package. I wonder if there is a way to use dates in axis labels? I think they are converted to integer by default. I want to plot by date in the same way as `ggplot` does.

```r
d <- seq(as.Date("2023-01-01"), as.Date("2023-12-31"), by = "1 day")
dat <- data.frame(date = d, val = rnorm(length(d)))

ggmatplot::ggmatplot(dat$date, dat[,"val", drop = FALSE])
ggplot2::ggplot(dat, aes(date, val)) + geom_point()
```
![image](https://github.com/xuan-liang/ggmatplot/assets/6572963/c711a70b-9272-4488-8d21-23205a6b5236)

![image](https://github.com/xuan-liang/ggmatplot/assets/6572963/7623e6a4-643a-47f1-bf13-e71dc856d82c)

**Comment by emitanaka** [comment]
Thank you for raising this, along with a reproducible example. This is certainly a bug. I'll try to fix this.

**Comment by emitanaka** [comment]
This is now fixed. Please reinstall the latest github version. Thanks again for raising this issue!

**Comment by koheiw** [comment]
@emitanaka thank you very much for fixing so quickly. I could plot dates in the same way as ggplot2 does!

**Comment by koheiw** [comment]
The Github version plots dates correctly when there is only one variable, but it is still converts dates to integer when there are more than one variables. I hope you can fix this easily.

```r
d <- seq(as.Date("2023-01-01"), as.Date("2023-12-31"), by = "1 day")
dat2 <- data.frame(date = d, val1 = rnorm(length(d)), val2 = rnorm(length(d)))

ggmatplot::ggmatplot(dat2$date, dat2[c("val1")])
ggmatplot::ggmatplot(dat2$date, dat2[c("val1", "val2")])
```

![image](https://github.com/xuan-liang/ggmatplot/assets/6572963/9cbcb98d-c404-475a-bb28-81947882977f)

![image](https://github.com/xuan-liang/ggmatplot/assets/6572963/58a5b700-a1c3-4177-b612-cb69fd812c00)

**Comment by emitanaka** [comment]
Thank you for letting us know again! You are right that it had a bug for ncol > 1. I have fixed this now for ncol > 1 (provided the other variable is a vector).

**Comment by koheiw** [comment]
Beautiful! Thank you very much!

![image](https://github.com/xuan-liang/ggmatplot/assets/6572963/cb7544bb-e8fc-4823-94a0-6b13d26a09c7)

**Comment by koheiw** [comment]
It seems that the same issue came back. This time dates become integer in both cases.

![image](https://github.com/user-attachments/assets/dac972cf-3ba6-4412-b26d-6e68ac1c1d90)

![image](https://github.com/user-attachments/assets/62fb156c-767a-43ad-b35a-c2fd0e5ab9c1)

```
> sessionInfo()
R version 4.4.1 (2024-06-14 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 11 x64 (build 26100)

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: Asia/Tokyo
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggmatplot_0.1.2 ggplot2_3.5.1  
```

**Comment by koheiw** [comment]
I noticed that the CRAN version is still old. I hope you have time submit your package to CRAN soon.
